/**
 * Server-side document export generators for the "Extract Info" feature.
 * Produces .docx (Word) and .xlsx (Excel) binary/AAB buffers that the export
 * API route can stream back for download. CSV is plain text.
 */

import { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, AlignmentType, HeadingLevel } from "docx";
import ExcelJS from "exceljs";

export interface ExportColumn {
  name: string;
  type: string;
}

export interface ExportData {
  title: string;
  columns: ExportColumn[];
  rows: Array<Record<string, string>>;
  generatedAt: string;
}

/**
 * Generate a Word (.docx) buffer for the extracted data.
 */
export async function generateDocx(data: ExportData): Promise<Buffer> {
  const headerRows: string[] = data.columns.map((c) => c.name);

  const tableRows: TableRow[] = [
    new TableRow({
      tableHeader: true,
      children: headerRows.map(
        (h) =>
          new TableCell({
            children: [
              new Paragraph({ children: [new TextRun({ text: h, bold: true })] }),
            ],
          })
      ),
    }),
    ...data.rows.map(
      (row) =>
        new TableRow({
          children: data.columns.map(
            (col) =>
              new TableCell({
                children: [
                  new Paragraph({ children: [new TextRun({ text: row[col.name] || "" })] }),
                ],
              })
          ),
        })
    ),
  ];

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: data.title, bold: true })],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated by Judmi Academy • ${data.generatedAt}`,
                italics: true,
                size: 18,
              }),
            ],
          }),
          new Paragraph({ children: [] }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: tableRows,
          }),
        ],
      },
    ],
  });

  return Packer.toBuffer(doc);
}

/**
 * Generate an Excel (.xlsx) buffer for the extracted data.
 */
export async function generateExcel(data: ExportData): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Judmi Academy";
  const sheet = workbook.addWorksheet(data.title.slice(0, 31) || "Extracted Data");

  sheet.columns = data.columns.map((col) => ({
    header: col.name,
    key: col.name,
    width: Math.max(18, col.name.length + 4),
  }));

  sheet.getRow(1).font = { bold: true };
  sheet.getRow(1).fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF4F46E5" },
  };
  sheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };

  for (const row of data.rows) {
    const excelRow: Record<string, string> = {};
    for (const col of data.columns) {
      excelRow[col.name] = row[col.name] || "";
    }
    sheet.addRow(excelRow);
  }

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/**
 * Generate a comma-separated values (CSV) string for the extracted data.
 */
export function generateCsv(data: ExportData): string {
  const esc = (val: string) => {
    const s = val == null ? "" : String(val);
    if (/[",\n\r]/.test(s)) {
      return `"${s.replace(/"/g, '""')}"`;
    }
    return s;
  };

  const header = data.columns.map((c) => esc(c.name)).join(",");
  const lines = data.rows.map((row) =>
    data.columns.map((col) => esc(row[col.name] || "")).join(",")
  );

  return [header, ...lines].join("\n");
}
